version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    #command: bundle exec unicorn_rails -C config/unicorn.rb
    volumes:
      - .:/WebApp
      - public-data:/WebApp/public
      - tmp-data:/WebApp/tmp
      - log-data:/WebApp/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/Prog/Myapp/WebApp/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/WebApp/public
      - tmp-data:/WebApp/tmp
    ports:
      - 8080:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
