default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'shuta13' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { '5112907' } %>
  host: db

development:
  <<: *default
  database: WebApp_development

test:
  <<: *default
  database: WebApp_test
